pipeline {
    agent any

    environment {
        SERVICE_DIR = "Auth-Service"
        IMAGE_NAME = "auth-service-image"
        CONTAINER_NAME = "auth-service"
    }

    stages {

        stage('Fix mvnw Permission') {
            steps {
                echo "Fixing mvnw execution permission..."
                sh "chmod +x ${SERVICE_DIR}/mvnw"
            }
        }

        stage('Build (Maven)') {
            steps {
                dir("${SERVICE_DIR}") {
                    echo "Building JAR..."
                    sh "./mvnw -B -DskipTests clean package"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image..."
                sh "docker build -t ${IMAGE_NAME} ${SERVICE_DIR}"
            }
        }

        stage('Deploy to EC2 (Docker)') {
            steps {
                echo "Stopping old container..."
                sh """
                    docker stop ${CONTAINER_NAME} || true
                    docker rm ${CONTAINER_NAME} || true
                """

                echo "Starting new container..."
                sh """
                    docker run -d --name ${CONTAINER_NAME} -p 8081:8081 ${IMAGE_NAME}
                """
            }
        }
    }

    post {
        failure {
            echo "Build failed!"
        }
        success {
            echo "Build & Deployment successful!"
        }
    }
}
